version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/python:3.9

jobs:
  build:
    executor: docker-executor

    steps:
      - checkout

      - run:
          name: Build Docker Image
          command: |
            docker build -t your-image-name:${CIRCLE_SHA1} .
            docker login -u $masettyabhishek -p navfyx-0sukhe-nexcEq
            docker push your-image-name:${CIRCLE_SHA1}
